// app/layout.tsx or app/layout.ts

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

// Load Nunito font using next/font/google
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
